# Generated by Django 4.1.7 on 2023-03-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
